version: 2
jobs:
  build:
    docker:
      - image: 218546966473.dkr.ecr.us-east-1.amazonaws.com/circle-ci:stitch-tap-tester-uv
    steps:
      - checkout
      - run:
          name: 'Setup virtual env'
          command: |
            uv venv --python 3.12 /usr/local/share/virtualenvs/tap-twilio
            source /usr/local/share/virtualenvs/tap-twilio/bin/activate
            uv pip install -U pip setuptools
            uv pip install .[dev]
      - run:
          name: 'pylint'
          command: |
            source /usr/local/share/virtualenvs/tap-twilio/bin/activate
            pip install pylint
            pylint tap_twilio -d C,R,W
      - add_ssh_keys
      - run:
          name: 'JSON Validator'
          command: |
            source /usr/local/share/virtualenvs/tap-tester/bin/activate
            stitch-validate-json tap_twilio/schemas/*.json
      - run:
          name: 'Integration Tests'
          command: |
            source /usr/local/share/virtualenvs/tap-tester/bin/activate
            uv pip install --upgrade awscli
            aws s3 cp s3://com-stitchdata-dev-deployment-assets/environments/tap-tester/tap_tester_sandbox dev_env.sh
            source dev_env.sh
            run-test --tap=tap-twilio tests
workflows:
  version: 2
  commit:
    jobs:
      - build:
          context: circleci-user
  build_daily:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build:
          context: circleci-user
